import type { User } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useForm } from "react-hook-form";

import { trpc } from "../utils/trpc";

type FormFieldValues = {
  walletAddress: string;
  alturaGuardCode: string;
};

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const { register, handleSubmit } = useForm<FormFieldValues>();
  const authMutation = trpc.altura.auth.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="modal modal-open">
          <div className="modal-box">
            <form
              onSubmit={handleSubmit((values) => {
                authMutation
                  .mutateAsync(values)
                  .then((res: User) => console.log(res));
              })}
            >
              <h3 className="text-lg font-bold">Login</h3>
              <div className="mb-5">
                <label className="pr-5">Wallet Address</label>
                <input
                  className="input-bordered input w-full"
                  {...register("walletAddress")}
                />
              </div>
              <div>
                <label className="pr-5">Altura Guard Code</label>
                <input
                  className="input-bordered input w-full"
                  {...register("alturaGuardCode")}
                />
              </div>
              <div className="modal-action">
                <button
                  type="submit"
                  className="btn mt-5 rounded-md border border-orange-500 p-1"
                >
                  Login
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
